import './globals.css'
import type { Metadata } from 'next'
import { Bangers } from 'next/font/google'

const bangers = Bangers({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bangers.className}>{children}</body>
    </html>
  )
}
